// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv9NpQtJRyghAp19FHwqaL-HnCyUPoBj0',
    appId: '1:862468269957:web:68734769b6c7d7de1106ec',
    messagingSenderId: '862468269957',
    projectId: 'moderern-store',
    authDomain: 'moderern-store.firebaseapp.com',
    storageBucket: 'moderern-store.firebasestorage.app',
    measurementId: 'G-Q0MB4NN4ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKxQb9HLqTGeEYHFicAo6bKOY6gkjdp1c',
    appId: '1:862468269957:android:759c4c54d4ee0b0a1106ec',
    messagingSenderId: '862468269957',
    projectId: 'moderern-store',
    storageBucket: 'moderern-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm6eIv3oSLXXGdw7NPRMLf5bUuGqQ61MY',
    appId: '1:862468269957:ios:d72936e8f7c2ce0c1106ec',
    messagingSenderId: '862468269957',
    projectId: 'moderern-store',
    storageBucket: 'moderern-store.firebasestorage.app',
    iosBundleId: 'com.example.modernGrocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm6eIv3oSLXXGdw7NPRMLf5bUuGqQ61MY',
    appId: '1:862468269957:ios:d72936e8f7c2ce0c1106ec',
    messagingSenderId: '862468269957',
    projectId: 'moderern-store',
    storageBucket: 'moderern-store.firebasestorage.app',
    iosBundleId: 'com.example.modernGrocery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv9NpQtJRyghAp19FHwqaL-HnCyUPoBj0',
    appId: '1:862468269957:web:de426756518c904d1106ec',
    messagingSenderId: '862468269957',
    projectId: 'moderern-store',
    authDomain: 'moderern-store.firebaseapp.com',
    storageBucket: 'moderern-store.firebasestorage.app',
    measurementId: 'G-WRZ270R3HP',
  );
}
